services:
    command_bus:
        alias: simple_bus.command_bus

    simple_bus.command_bus:
        class: SimpleBus\Message\Bus\Middleware\MessageBusSupportingMiddleware
        public: false
        tags:
            - { name: message_bus, type: command, middleware_tag: command_bus_middleware }

    simple_bus.command_bus.delegates_to_message_handler_middleware:
        class: SimpleBus\Message\Handler\DelegatesToMessageHandlerMiddleware
        public: false
        arguments:
            - @simple_bus.command_bus.command_handler_resolver
        tags:
            - { name: command_bus_middleware, priority: -1000 }

    simple_bus.command_bus.class_based_command_name_resolver:
        class: SimpleBus\Message\Name\ClassBasedNameResolver
        public: false

    simple_bus.command_bus.named_message_command_name_resolver:
        class: SimpleBus\Message\Name\NamedMessageNameResolver
        public: false

    simple_bus.command_bus.command_handler_map:
        class: SimpleBus\Message\Handler\Map\LazyLoadingMessageHandlerMap
        public: false
        arguments:
            # collection of command handler service ids, will be provided by the RegisterHandlers compiler pass
            - []
            - @simple_bus.command_bus.invokable_service_locator

    simple_bus.command_bus.command_handler_resolver:
        class: SimpleBus\Message\Handler\Resolver\NameBasedMessageHandlerResolver
        public: false
        arguments:
            - @simple_bus.command_bus.command_name_resolver
            - @simple_bus.command_bus.command_handler_map

    simple_bus.command_bus.invokable_service_locator:
        class: SimpleBus\SymfonyBridge\DependencyInjection\InvokableServiceLocator
        public: false
        arguments:
            - @service_container

    simple_bus.command_bus.finishes_command_before_handling_next_middleware:
        class: SimpleBus\Message\Bus\Middleware\FinishesHandlingMessageBeforeHandlingNext
        public: false
        tags:
            - { name: command_bus_middleware, priority: 1000 }
